# Generated by Django 6.0.2 on 2026-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingslot_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='vehicle_model',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], default='FREE', max_length=10),
        ),
    ]
