# Generated by Django 6.0.2 on 2026-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_remove_parkingslot_vehicle_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='owner',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
